# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car_payload.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='car_payload.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11\x63\x61r_payload.proto\"\xb4\x01\n\x11\x43\x61rTrackerPayload\x12)\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x19.CarTrackerPayload.Action\x12$\n\ncreate_car\x18\x02 \x01(\x0b\x32\x10.CreateCarAction\x12$\n\nupdate_car\x18\x03 \x01(\x0b\x32\x10.UpdateCarAction\"(\n\x06\x41\x63tion\x12\x0e\n\nCREATE_CAR\x10\x00\x12\x0e\n\nUPDATE_CAR\x10\x01\"\x9f\x01\n\x0f\x43reateCarAction\x12\x0f\n\x07\x63hassis\x18\x01 \x01(\t\x12\x0f\n\x07license\x18\x02 \x01(\t\x12\r\n\x05\x63olor\x18\x03 \x01(\t\x12\r\n\x05\x62rand\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\x18\n\x10yearManufactured\x18\x06 \x01(\x05\x12\x11\n\tyearModel\x18\x07 \x01(\x05\x12\x10\n\x08\x61gent_id\x18\x08 \x01(\t\"8\n\x0fUpdateCarAction\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x13\n\x0bkilometrage\x18\x02 \x01(\x04\x62\x06proto3'
)



_CARTRACKERPAYLOAD_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='CarTrackerPayload.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_CAR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE_CAR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=162,
  serialized_end=202,
)
_sym_db.RegisterEnumDescriptor(_CARTRACKERPAYLOAD_ACTION)


_CARTRACKERPAYLOAD = _descriptor.Descriptor(
  name='CarTrackerPayload',
  full_name='CarTrackerPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='CarTrackerPayload.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_car', full_name='CarTrackerPayload.create_car', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_car', full_name='CarTrackerPayload.update_car', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CARTRACKERPAYLOAD_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=202,
)


_CREATECARACTION = _descriptor.Descriptor(
  name='CreateCarAction',
  full_name='CreateCarAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chassis', full_name='CreateCarAction.chassis', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='license', full_name='CreateCarAction.license', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='CreateCarAction.color', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brand', full_name='CreateCarAction.brand', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='CreateCarAction.model', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yearManufactured', full_name='CreateCarAction.yearManufactured', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yearModel', full_name='CreateCarAction.yearModel', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='CreateCarAction.agent_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=364,
)


_UPDATECARACTION = _descriptor.Descriptor(
  name='UpdateCarAction',
  full_name='UpdateCarAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='UpdateCarAction.agent_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kilometrage', full_name='UpdateCarAction.kilometrage', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=422,
)

_CARTRACKERPAYLOAD.fields_by_name['action'].enum_type = _CARTRACKERPAYLOAD_ACTION
_CARTRACKERPAYLOAD.fields_by_name['create_car'].message_type = _CREATECARACTION
_CARTRACKERPAYLOAD.fields_by_name['update_car'].message_type = _UPDATECARACTION
_CARTRACKERPAYLOAD_ACTION.containing_type = _CARTRACKERPAYLOAD
DESCRIPTOR.message_types_by_name['CarTrackerPayload'] = _CARTRACKERPAYLOAD
DESCRIPTOR.message_types_by_name['CreateCarAction'] = _CREATECARACTION
DESCRIPTOR.message_types_by_name['UpdateCarAction'] = _UPDATECARACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CarTrackerPayload = _reflection.GeneratedProtocolMessageType('CarTrackerPayload', (_message.Message,), {
  'DESCRIPTOR' : _CARTRACKERPAYLOAD,
  '__module__' : 'car_payload_pb2'
  # @@protoc_insertion_point(class_scope:CarTrackerPayload)
  })
_sym_db.RegisterMessage(CarTrackerPayload)

CreateCarAction = _reflection.GeneratedProtocolMessageType('CreateCarAction', (_message.Message,), {
  'DESCRIPTOR' : _CREATECARACTION,
  '__module__' : 'car_payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateCarAction)
  })
_sym_db.RegisterMessage(CreateCarAction)

UpdateCarAction = _reflection.GeneratedProtocolMessageType('UpdateCarAction', (_message.Message,), {
  'DESCRIPTOR' : _UPDATECARACTION,
  '__module__' : 'car_payload_pb2'
  # @@protoc_insertion_point(class_scope:UpdateCarAction)
  })
_sym_db.RegisterMessage(UpdateCarAction)


# @@protoc_insertion_point(module_scope)
